---
- name: Get OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: "setup-{{ ansible_os_family }}.yml"

- name: Install docker
  package:
    name: "{{ docker_packages }}"
    state: present
  notify: restart docker

- name: Manage the docker service
  service:
    name: "{{ docker_service_name }}"
    enabled: "{{ docker_service_enabled }}"
    state: "{{ docker_service_state }}"
