---
- name: Install docker yum repo
  yum_repository:
    name: docker
    description: Docker yum repo
    baseurl: "{{ docker_package_repo }}/{{ ansible_distribution_major_version }}/$basearch/edge"
    gpgcheck: true
    gpgkey: "{{ docker_package_repo_key }}"
    enabled: true
  when: ansible_pkg_mgr == 'yum'

- name: Install docker dnf repo
  get_url:
    url: "{{ docker_package_repo_file }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  when: ansible_pkg_mgr == 'dnf'
